listen_port: "8081"

log_path: ""

db_type: "mysql"
db_user: "root"
db_pwd: "12345678"
db_host: "127.0.0.1"
db_port: 3306
db_name: "srilanka"

# useful only if db_type sqlite
sqlite_db_name: "srilanka.db"

token_secret: "srilanka"
